### ISSUE TITLE
ConnectTimeout: HTTPSConnectionPool

### ISSUE THREAD

**Issue by Denyreal** [proxmoxer/proxmoxer#111]
Hi 

Thank you for writing proxmoxer it will make my life easier.

**As a noob with ansible and modules** i don't get how to setup this module to disable ssl verification : 

Then i got this kind of error : 

` The error was: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='curiosity', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f21f8f679d0>, 'Connection to curiosity timed out. (connect timeout=5)'))`

I see we can setup : 'verify_ssl=False' or chane the backend for openssh but **as a complete novice** i got no idea in which file i need to write the setting.

Can someone give me a hint please ?

Thanks you in advance.

**Comment by jhollowe** [comment]
So that error is from using the (default) HTTPS backend. If you are wanting to SSH, you will use the `backend` argument (see [the docs](https://proxmoxer.github.io/docs/1.2/basic_usage/#switching-services-or-backends)). If the HTTPS backend will work for you, you just need to add `verify_ssl = False` to where you are creating the ProxmoxAPI object ([docs](https://proxmoxer.github.io/docs/1.2/basic_usage/#importing-and-creating-an-instance)).

**Comment by jhollowe** [comment]
All the instructions in the docs are for directly using proxmoxer. Since you are using Ansible, you will need to look at what parameters and configuration is supported by it.

I believe [this is the Ansible documentation for the proxmox module](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html)

> I thought doing :
> `pip install proxmoxer requests openssh_wrapper paramiko`

>was ok and i just needed to add some env variables.

yeah, that is all that needs to be installed with PIP. What that section is talking about (and probably could stand to be worded better) is that when you are directly using proxmoxer in Python, you have to import the proxmoxer library and then create a ProxmoxerAPI object using the credentials and configuration that you want.

**Comment by jhollowe** [comment]
please repoen if you are still having issues with proxmoxer.
