### ISSUE TITLE
Update description in vm config

### ISSUE THREAD

**Issue by areqq** [proxmoxer/proxmoxer#152]
How to update 'description' in config?

vm = proxmox.nodes('proxmox6').qemu('101')
vm.config.update({'description': '#test\ntest2\n'})

Don't work.

**Comment by morph027** [comment]
Try

`vm.config.post(description="#test\ntest2\n")`

**Comment by areqq** [comment]
it works, thanks!

**Comment by aznashwan** [comment]
@areqq it looks like Proxmoxer DOES properly send newlines to the server and they do get properly saved:

### Checks

```python3
vmcli = proxmox.nodes("proxmox03").qemu(500)

MULTILINE_DESCR = """
Line 1
Line 2
Line 3
""".strip("\n")

vmcli.config.set(description=MULTILINE_DESCR)

# Works:
assert vmcli.config.get()["description"] == MULTILINE_DESCR
```

The problem is that the Web UI is rendering HTML, so `\n` will basically be ignored.

### Solution

What we need to do is "HTML-ify" the description a bit by replacing `\n` with `<br>`. (HTML line break)

```python3
html_description = MULTILINE_DESCR.replace('\n', '<br>')

vmcli.config.set(description=html_description)
```

**Comment by areqq** [comment]
Thank you very much for your detailed explanation
