### ISSUE TITLE
501 Not Implemented

### ISSUE THREAD

**Issue by marvelman3284** [proxmoxer/proxmoxer#54]
I just finished setting up my proxmox server and had wanted to try this out. After copying the example in the readme (the PVE one) I ran it and was greeted with this error:

```
Traceback (most recent call last):
  File "/run/media/marvel/data/Coding/python_in_proxmox/main.py", line 9, in <module>
    for vm in proxmox.nodes(node['node']).openvz.get():
  File "/home/marvel/.local/lib/python3.9/site-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/home/marvel/.local/lib/python3.9/site-packages/proxmoxer/core.py", line 90, in _request
    raise ResourceException("{0} {1}: {2} - {3}".format(
proxmoxer.core.ResourceException: 501 Not Implemented: Method 'GET /nodes/lab/openvz' not implemented - b'{"data":null}'
```

I am running this on arch linux with python 3.9.

Thanks in advance

**Comment by jhollowe** [comment]
What version of PVE and proxmoxer are you using?

**Comment by marvelman3284** [comment]
> What version of PVE and proxmoxer are you using? What backend are you using?

PVE: 6.4-4/337d6701
Proxmoxer: 1.1.1
And I am not sure what you mean by backend. Here is my code if that helps:
```py 
from proxmoxer import ProxmoxAPI

proxmox = ProxmoxAPI(host="ip here",
                     user='root@pam',
                     password='password here',
                     verify_ssl=False)

for node in proxmox.nodes.get():
    for vm in proxmox.nodes(node['node']).openvz.get():
        print("{0}. {1} => {2}".format(vm['vmid'], vm['name'], vm['status']))
```

**Comment by jhollowe** [comment]
Looking at the [APIv2 explorer](https://pve.proxmox.com/pve-docs/api-viewer/index.html), it looks like it should be either `qemu` for VMs or `lxc` for containers instead of `openvz`.

There are a lot of issues and outdated code in the README. Feel free to create a PR to fix this issue, but I'm planning to streamline the readme a lot and move some of the more complicated examples into the (currently non-existent) wiki for this repo (hopefully over the summer).

**Comment by marvelman3284** [comment]
Ok thanks
